### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by Kittnz** [System25/drxtract#11]
Hey

Was wondering if this would work on a windows system as well?
Ive got an old director game which i want to remake on something more modern.

When i try the main script it find it but then all other scripts are not found for unknown reason.

Any help or input would be appriciated!
Discord: Kittnz#1582

**Comment by System25** [comment]
Hi, if you use python for Windows it will probably work partially (because you also need ImageMagic and FFmpeg), but it is not tested.

If I were you I would try installing Cygwin (https://www.cygwin.com/) in your Windows with the python3, ImageMagic and FFmpeg packages and running drxtract with it.

Best regards!
