### ISSUE TITLE
bitd2bmp not found

### ISSUE THREAD

**Issue by gmarty** [System25/drxtract#6]
I'm running `drxtract` on Mac with Python 3.7.7 and I get the following error message when I try to extract a .dxr file:
```
$ python3 drxtract mac ../cd/data/st.dxr ../stdxr
[...]
sh: /bitd2bmp: No such file or directory
```

**Comment by System25** [comment]
Hi, you must run it like this:
`  ./drxtract mac ../cd/data/st.dxr ../stdxr`

The "./" is important because that path will be used as the base path to run the scripts.
So, setting the "./" in "**.**/drxtract" it will run "**.**/bitd2bmp".

If you use a folder it will work too. And "./drxtract/drxtract" will run "./drxtract/bitd2bmp".

Best regards!

**Comment by gmarty** [comment]
Great! It worked and I don't have this error message now.
Thank you!
